### ISSUE TITLE
Use EFO (not efo) as CURIEs

### ISSUE THREAD

**Issue by cmungall** [ga4gh/cat-vrs#39]
The preferred prefix for EFO is `EFO`
https://bioregistry.io/registry/efo

And also on the official OLS browser:
https://www.ebi.ac.uk/ols4/ontologies/efo/classes?short_form=EFO_0030069

**Comment by korikuzma** [comment]
@ga4gh/vr-maintainers This is also incorrect in VRS https://github.com/ga4gh/vrs/blob/664cd9f051bab3ec5d5d7da2c2387d529dadfa0e/schema/vrs/vrs-source.yaml#L232-L239 . Since `copyChange` is in `ga4ghDigest.keys` this change would cause VRS Copy Number Change computed identifiers to change.

**Comment by korikuzma** [comment]
Follow up: The prefix is lowercase in https://registry.identifiers.org/registry/efo

**Comment by jsstevenson** [comment]
> Follow up: The prefix is lowercase in https://registry.identifiers.org/registry/efo

also in [bioportal](https://bioportal.bioontology.org/ontologies/EFO/?p=classes&conceptid=root) albeit with a different LUI pattern (oof)

**Comment by ahwagner** [comment]
I agree with @cmungall. We had settled on all namespaces as lowercase in VRS v1.3 (similar inconsistencies exist with many CURIE namespaces) but with advancements in GKS common lib it now makes more sense to promote the convention preferred by EMBL-EBI as the EFO authority. This should apply to VRS 2.0 and forward. Since Cat-VRS uses VRS 2.0 I am okay with this proposed change.

We will not change VRS 1.3 CNX class since (as @korikuzma correctly pointed out) this would be a breaking change.
